name: "Terraform EC2 Deployment"

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf' # Trigger bei Änderungen an Terraform-Dateien
  pull_request:
    branches:
      - main

env:
  TF_LOG: INFO # Terraform-Log-Verbosity
  AWS_REGION: "eu-central-1" # AWS-Region

jobs:
  terraform:
    name: "Deploy EC2 Instance"
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Terraform installieren
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      # Terraform initialisieren
      - name: Initialize Terraform
        run: terraform init

      # Formatierung prüfen
      - name: Check Terraform Format
        run: terraform fmt -check

      # Konfiguration validieren
      - name: Validate Terraform Configuration
        run: terraform validate

      # Plan erstellen (bei Pull Requests)
      - name: Generate Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -out=tfplan

      # Plan anwenden (bei Push auf main)
      - name: Apply Terraform Plan
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
